region: 
  name: 'Region'
  data: {'Northeast': 'Northeast', 'South': 'South', 'West': 'West', 'Midwest': 'Midwest'}
  comp: "equal"
  col: "Region"
  error: 'We cannot find your region'
price: 
  name: 'Price'
  data: {'$0 - $100000': [0, 100000] , '$100000 - $300000': [100000, 300000] , '$300000 - $600000': [300000, 600000] , '$600000 - $1000000': [600000, 1000000], '$1000000 - $1500000': [1000000, 1500000] , '$1500000 - $10000000': [1500000, 10000000]}
  comp: "range"
  col: 'Price'
  error: 'We cannot process your price range'
beds: 
  name: 'Number of Beds'
  data: {'1': 1, '2': 2, '3': 3, '4': 4, '5': 5}
  comp: "equal"
  col: 'Beds'
  error: 'We cannot process your number of beds'
rate: 
  name: 'Mortgage Rate'
  data: {'6%': 6, '5%': 5, '4%': 4, '2%': 2}
  comp: "na"
  col: 'na'
  error: 'We cannot process your mortgage rate'
timeline: 
  name: 'Timeline'
  data: {'30 years': 30, '20 years': 20, '15 years': 15, '10 years': 10, '7 years': 7, '5 years': 5, '3 years': 3}
  comp: "na"
  col: 'na'
  error: 'We cannot process your timeline'
forecast: 
  name: 'Sort By Price Forecast'
  data: {'True': True, 'False': False}
  comp: "na"
  col: 'na'
  error: 'Price Forecast must be a boolean value'
